alias learn='cd ~/Projects/canopy/CanopyLearn'
alias canopy='cd ~/Projects/canopy/CanopyWebsite'
alias cliqs='cd ~/Projects/cliqs'
alias ls="ls -G"
alias stub='bundle --binstubs=./bundler_stubs'
alias ttr='touch tmp/restart.txt'
alias pull='git pull origin master'
alias push='git push origin master'
alias cm='git commit -m $1'
alias migrateall='RAILS_ENV=development rake db:migrate; RAILS_ENV=test rake db:migrate'
alias repow='curl get.pow.cx | sh'